apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../mytra-site-bot.yaml
  - ../../../mytra-helm-charts.yaml
configMapGenerator:
  - name: site-values
    namespace: flux-system
    files:
      - values.yaml=../../../site-values.yaml
  - name: bot-default-values
    namespace: flux-system
    files:
      - values.yaml=../../bot-default-values.yaml
  - name: bot-specific-values
    namespace: flux-system
    files:
      - values.yaml=./bot.yaml
configurations:
  - ../../../kustomize-config.yaml
