apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../mytra-site-station.yaml
  - ../../../mytra-helm-charts.yaml
configMapGenerator:
  - name: site-values
    namespace: flux-system
    files:
      - values.yaml=../../../site-values.yaml
  - name: station-default-values
    namespace: flux-system
    files:
      - values.yaml=../../station-default-values.yaml
  - name: station-values
    namespace: flux-system
    files:
      - values.yaml=./station.yaml
  - name: photobooth-calibration-values
    namespace: flux-system
    files:
      - values.yaml=./photobooth-calibration-values.yaml
configurations:
  - ../../../kustomize-config.yaml
